Feature #8
JOHNKYON/Sora pull request #9
Opened 2018-05-08 12:46 UTC by JOHNKYON

Resolve #8

2018-05-08 14:21 UTC, ZhuGongpu requested changes

2018-05-08 14:21 UTC, ZhuGongpu commented on .travis.yml
> +  - pytest
Ensure an empty line at EOF.

Should also enforce an `.editorconfig` file.

2018-05-08 14:21 UTC, ZhuGongpu commented on test/test_null.py
> +    """Test case that do nothing"""
`Keep pytest happy`.

And add a issue ref on top.

2018-05-08 14:29 UTC, JOHNKYON commented on test/test_null.py
> +    """Test case that do nothing"""
Refuse issue ref.
Looks silly.

2018-05-08 14:31 UTC, JOHNKYON commented on .travis.yml
> +  - pytest
Leave .editconfig to another issue

2018-05-08 14:54 UTC, JOHNKYON commented on .travis.yml
> +  - pytest
Done with EOF.

2018-05-08 15:31 UTC, ZhuGongpu requested changes

2018-05-08 15:31 UTC, ZhuGongpu commented on .gitignore
>  .idea/**/workspace.xml
Redundant.

2018-05-08 15:31 UTC, ZhuGongpu commented on test/test_null.py
> +    """Test case that do nothing"""
Add references is designated for **readability** and **maintenance**.

2018-05-08 15:43 UTC, JOHNKYON commented on test/test_null.py
> +    """Test case that do nothing"""
Outer links will only decrease the readability. What if one day github gets **blocked** by the firewall?

2018-05-08 16:14 UTC, ZhuGongpu requested changes

2018-05-08 16:14 UTC, ZhuGongpu commented on .gitignore
> -# User-specific stuff
Should do this in the last commit.

2018-05-08 16:14 UTC, ZhuGongpu commented on test/test_null.py
> +    """Test case that do nothing"""
That is not the point.

Outer links, which may be GitHub Issues, StackOverflow or anything else, are just references telling some basic background information and design principles.

2018-05-09 01:42 UTC, JOHNKYON commented on test/test_null.py
> +    """Test case that do nothing"""
Which would decrease the robust. Robust code should be maintained by **non-specific** environment while too much information that does not stick to the code itself would distract people. Use GitHub Issues or anything like that to help develop, but never put everything on it.

2018-05-09 12:12 UTC, merged